# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-04 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[

            ],
        ),
    ]
